AWSTemplateFormatVersion: '2010-09-09'
Description: A sample Lambda Safe Deployment Application
Resources:
  encryptedBucket:
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
    Type: AWS::S3::Bucket
  encryptedTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: version
        AttributeType: N
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: version
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
    Type: AWS::DynamoDB::Table
  myFirstFunction:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://danilop/packages/2a9579cbb1f7b66ac4c3aecb0c40580b
      DeploymentPreference:
        Hooks:
          PreTraffic:
            Ref: preTrafficHook
        Type: Linear10PercentEvery1Minute
      Events:
        GetResource:
          Properties:
            Method: ANY
            Path: /first
          Type: Api
      Handler: myFirstFunction.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  mySecondFunction:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://danilop/packages/2a9579cbb1f7b66ac4c3aecb0c40580b
      DeploymentPreference:
        Hooks:
          PreTraffic:
            Ref: preTrafficHook
        Type: Canary10Percent5Minutes
      Events:
        GetResource:
          Properties:
            Method: ANY
            Path: /second
          Type: Api
      Handler: mySecondFunction.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  preTrafficHook:
    Properties:
      CodeUri: s3://danilop/packages/2a9579cbb1f7b66ac4c3aecb0c40580b
      DeploymentPreference:
        Enabled: false
      Environment:
        Variables:
          CurrentVersion:
            Ref: myFirstFunction.Version
          MetricName: Fitness
          Namespace:
            Ref: AWS::StackName
          StackId:
            Ref: AWS::StackId
      FunctionName: CodeDeployHook_preTrafficHook
      Handler: preTrafficHook.handler
      Policies:
      - Statement:
        - Action:
          - codedeploy:PutLifecycleEventHookExecutionStatus
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*
        Version: '2012-10-17'
      - Statement:
        - Action:
          - lambda:InvokeFunction
          Effect: Allow
          Resource:
          - Fn::GetAtt:
            - myFirstFunction
            - Arn
          - Ref: myFirstFunction.Version
          - Fn::GetAtt:
            - mySecondFunction
            - Arn
          - Ref: mySecondFunction.Version
        Version: '2012-10-17'
      - Statement:
        - Action:
          - cloudformation:ListStackResources
          Effect: Allow
          Resource:
            Ref: AWS::StackId
        Version: '2012-10-17'
      - Statement:
        - Action:
          - cloudwatch:putMetricData
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      - Statement:
        - Action:
          - s3:GetEncryptionConfiguration
          Effect: Allow
          Resource:
          - Fn::GetAtt:
            - encryptedBucket
            - Arn
          - Fn::GetAtt:
            - unencryptedBucket
            - Arn
        Version: '2012-10-17'
      - Statement:
        - Action:
          - dynamodb:DescribeTable
          Effect: Allow
          Resource:
          - Fn::GetAtt:
            - encryptedTable
            - Arn
          - Fn::GetAtt:
            - unencryptedTable
            - Arn
        Version: '2012-10-17'
      - Statement:
        - Action:
          - config:GetComplianceDetailsByResource
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      Runtime: nodejs8.10
      Timeout: 60
    Type: AWS::Serverless::Function
  unencryptedBucket:
    Type: AWS::S3::Bucket
  unencryptedTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: version
        AttributeType: N
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: version
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
